Description: >

    This template construct from the aws, using the basic structure of setting up vpc, security-groups, load-balancers,
    and a ecs cluster, the purpose is quick and easy set up a environment for automation deployment of ecs service.
    
Parameters:

    ClusterSize: 
        Description: How many instances of this task should we run across our cluster?
        Type: Number
        Default: 2

    InstanceType:
        Description: Which instance type should we use to build the ECS cluster?
        Type: String
        Default: c4.large

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/adexmohuicloudformations/infrastructure/VPC/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                VpcCIDR:            172.16.0.0/16
                PublicSubnet1CIDR:  172.16.8.0/21
                PublicSubnet2CIDR:  172.16.16.0/21
                PrivateSubnet1CIDR: 172.16.24.0/21
                PrivateSubnet2CIDR: 172.16.32.0/21

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/adexmohuicloudformations/infrastructure/SecurityGroups/security-groups.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/adexmohuicloudformations/infrastructure/LoadBalancers/load-balancers.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/adexmohuicloudformations/infrastructure/ECS/ecs-cluster.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                InstanceType: !Ref InstanceType
                ClusterSize: !Ref ClusterSize
                VPC: !GetAtt VPC.Outputs.VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets


Outputs:

    WebsiteServiceUrl: 
        Description: The URL endpoint for the website service
        Value: !Join ["", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "/" ]]
